parameters:
  deployments: string

steps:
  - template: template.step.install.tflint.yml
    parameters:
      version: $(tflint)
      sha: $(tflint_sha256)

  - task: Bash@3
    displayName: "Run TFLint"
    inputs:
      targetType: "inline"
      script: |
        IFS=' ' read -r -a array <<< "${{ parameters.deployments }}"

        #TFLINT_LOG=debug tflint

        for deployment in "${array[@]}"
        do
          echo "START linting ${deployment}"
          if [[ "$(tflint "$(workDir)/${deployment}" | wc -l)" -gt 0 ]]; then
            filePath=$(echo "${deployment}.xml" | sed -e 's/\//-/g')
            tflint "$(workDir)/$deployment" > "$filePath"
            echo "##vso[task.addattachment type=Distributedtask.Core.Summary;name=TFLint-$filePath-Results;]$(pwd)/$filePath"
            echo "##vso[task.logissue type=error]${deployment} failed tflint scan."
            exitcode=1
          else
            echo "TFLint passed."
          fi
          echo "END linting ${deployment}"

        done
      failOnStderr: true
