parameters:
  - name: environment
    type: string
    default: ""

steps:
  - task: DownloadSecureFile@1
    displayName: "Download Environment File"
    inputs:
      secureFile: "${{ parameters.environment }}.compiled.env"

  - task: Bash@3
    displayName: "Setup env: ${{ parameters.environment }}"
    inputs:
      targetType: "inline"
      script: |
        #Apply .env file to shell
        set -o allexport && . $(Agent.TempDirectory)/${{ parameters.environment }}.compiled.env && set +o allexport

        for var in `env | sort`; do
          if [[ $var =~ ^TF_VAR_.* ]]; then
            key=`echo $var | cut -d'=' -f1` 	
            echo ${!key}
            echo "##vso[task.setvariable variable=$key]${!key}"
          fi
        done

        echo "Environment: "${{ parameters.environment }}
        # env | sort
